### ISSUE TITLE
Single Brackets on app name brakes gym command

### ISSUE THREAD

**Issue by lucoceano** [fastlane/gym#107]
When my app name has single brackes this command fails:

```
set -o pipefail && xcodebuild -workspace './appname.xcworkspace' -scheme 'appname' -destination 'generic/platform=iOS' -archivePath '~/builds/_.4.8/archives/appname.xcarchive' archive | tee '~/builds/_.4.8/archives/appname.log/APP 'NAME-appname.log' | xcpretty
```
the stacktrace:

```
-----
-----c: line 1: syntax error: unexpected end of file         

sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
[11:40:42]: Exit status: 2
/Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/error_handler.rb:52:in `handle_build_error': Error building the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/runner.rb:80:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.17.1/lib/fastlane_core/command_executor.rb:51:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.17.1/lib/fastlane_core/command_executor.rb:51:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/runner.rb:76:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/commands_generator.rb:58:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/lib/gym/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.8.2/bin/gym:6:in `<top (required)>'
	from /usr/bin/gym:23:in `load'
	from /usr/bin/gym:23:in `<main>'
```

**Comment by CBeloch** [comment]
Have the same issue

```bash
▸ Signing path/to/MyApp.app
▸ Touching MyApp.app.dSYM
[11:11:24]: Exit status: 1
/Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/error_handler.rb:52:in `handle_build_error': Error building the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/runner.rb:80:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.22.2/lib/fastlane_core/command_executor.rb:62:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.22.2/lib/fastlane_core/command_executor.rb:62:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/runner.rb:76:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/commands_generator.rb:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/lib/gym/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-0.9.0/bin/gym:6:in `<top (required)>'
	from /usr/bin/gym:23:in `load'
	from /usr/bin/gym:23:in `<main>'
```

Had a CFBundleDisplayName with "ü" and ":" and removed it, still same issue... 
My exit code is different. Updated gym to latest version (0.9.0)

**Comment by HughJeffner** [comment]
Single quote in the product name causes similar crash as well.  I think it has to do something with the `.log` file since it never gets generated.

```
[08:45:35]: $ set -o pipefail && xcodebuild -scheme 'Scheme Name' -project './ProjectName.xcodeproj' -destination 'generic/platform=iOS' -archivePath '/Users/User/Library/Developer/Xcode/Archives/2016-01-05/Scheme Name 2016-01-05 08.45.35.xcarchive' archive | tee '/Users/User/Library/Logs/gym/Product's Name-Scheme Name.log' | xcpretty
[08:45:35]: ▸ sh: -c: line 0: unexpected EOF while looking for matching `''
[08:45:35]: ▸ sh: -c: line 1: syntax error: unexpected end of file
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
[08:45:35]: Exit status: 2
/Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/error_handler.rb:52:in `handle_build_error': Error building the application - see the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/runner.rb:81:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:61:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.32.0/lib/fastlane_core/command_executor.rb:61:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/runner.rb:77:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/runner.rb:10:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/manager.rb:8:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/commands_generator.rb:60:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/lib/gym/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.2.0/bin/gym:6:in `<top (required)>'
	from /usr/bin/gym:23:in `load'
	from /usr/bin/gym:23:in `<main>'

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1850. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
